### ISSUE TITLE
NullReferenceException setting Role permissions

### ISSUE THREAD

**Issue by rreaddev** [Sitefinity-SDK/Telerik.Sitefinity.Samples.Quantum#4]
NullReferenceException setting Role permissions for Multisite management.  Error log below.

Message: HandlingInstanceID: 2310f739-bef8-4ce8-b017-15b0e383feda
An exception of type 'System.NullReferenceException' occurred and was caught.
-----------------------------------------------------------------------------
04/13/2015 13:29:51
Type : System.NullReferenceException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089
Message : Object reference not set to an instance of an object.
Source : Unity_ILEmit_DynamicClasses
Help link : 
Data : System.Collections.ListDictionaryInternal
TargetSite : Void AddPermissionToObject(Telerik.Sitefinity.Security.Model.ISecuredObject, Telerik.Sitefinity.Data.IManager, Telerik.Sitefinity.Security.Model.Permission, System.String)
HResult : -2147467261
Stack Trace :    at DynamicModule.ns.Wrapped_OpenAccessMultisiteProvider_44d552d93e1d4cc0ab4e63ab4dbb6087.AddPermissionToObject(ISecuredObject securedObject, IManager managerInstance, Permission permission, String transactionName)
   at Telerik.Sitefinity.Data.ManagerBase`1.AddPermissionToObject(ISecuredObject securedObject, IManager managerInstace, Permission permission, String transactionName)
   at Telerik.Sitefinity.Security.Web.Services.Permissions.CreatePermissionForSecuredObject(IManager manager, ISecuredObject securedObject, Guid principalId, String permissionSetName, IList`1 allowedActions, IList`1 deniedActions)
   at Telerik.Sitefinity.Security.Web.Services.Permissions.SavePermissionActionsForSpecificPrincipal(List`1 principals, String permissionsSetName, String dataProviderName, String permissionObjectRootID, String managerClassName, Guid principalID, String securedObjectID, String securedObjectType, String dynamicDataProviderName)
   at SyncInvokeSavePermissionActionsForSpecificPrincipal(Object , Object[] , Object[] )
   at System.ServiceModel.Dispatcher.SyncMethodInvoker.Invoke(Object instance, Object[] inputs, Object[]& outputs)
   at System.ServiceModel.Dispatcher.DispatchOperationRuntime.InvokeBegin(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage5(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage41(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage4(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage31(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage3(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage2(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage11(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.ImmutableDispatchRuntime.ProcessMessage1(MessageRpc& rpc)
   at System.ServiceModel.Dispatcher.MessageRpc.Process(Boolean isOperationContextSet)

Additional Info:

TimeStamp : 4/13/2015 5:29:51 PM
FullName : Telerik.Sitefinity.Utilities, Version=8.0.5700.0, Culture=neutral, PublicKeyToken=b28c218413bdf563
AppDomainName : /LM/W3SVC/119/ROOT-1-130734194964908775
ThreadIdentity : 
WindowsIdentity : IIS APPPOOL\DefaultAppPool
Requested URL : http://localhost/Sitefinity/Services/Security/Permissions.svc/Site/OpenAccessDataProvider/?permissionObjectRootID=00000000-0000-0000-0000-000000000000&managerClassName=Telerik__dot__Sitefinity__dot__Multisite__dot__MultisiteManager&principalID=0e6ae40d-515d-67af-8bab-ff0100a58543&securedObjectID=c8a2e20d-515d-67af-8bab-ff0100a58543&securedObjectType=Telerik.Sitefinity.Security.Model.SecurityRoot, Telerik.Sitefinity.Model, Version=8.0.5700.0, Culture=neutral, PublicKeyToken=b28c218413bdf563&dynamicDataProviderName=null

Category: ErrorLog

Priority: 0

EventId: 90000

Severity: Error

Title:Enterprise Library Exception Handling

App Domain: /LM/W3SVC/119/ROOT-1-130734194964908775

ProcessId: 5976

Process Name: C:\Windows\SysWOW64\inetsrv\w3wp.exe

Thread Name: 

Win32 ThreadId:13320

Extended Properties:

**Comment by nader-dab** [comment]
Hello. I was not able to reproduce the issue. If you are still encountering the error, could you please provide more detailed steps on how to reproduce it. For which site are you trying to set new permissions (Axel, Quantum or Resseler Template)? What is the role you are trying to set?
